[package]
name = "hello-rust"
version = "0.0.1"
authors = ["linux@codehelp.co.uk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
